[package]
distribution = "2201.0.0"
org="ballerinax"
name = "redis"
version="2.2.0"
authors = ["Ballerina"]
keywords = ["IT Operations/Databases",  "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-redis"
license = ["Apache-2.0"]

[[platform.java11.dependency]]
path = "../redis-utils/target/redis-2.2.0.jar"
groupId = "org.ballerinalang"
artifactId = "redis-utils"
module = "redis-utils" 
version="2.2.0"
