[project]
org-name="wso2"
version="0.0.0"

[platform]
target = "java8"

[[platform.libraries]]
module = "redis"
path = "../redis-utils/target/redis-0.8.3-SNAPSHOT.jar"
artafactId = "redis"
version = "0.8.3-SNAPSHOT"
groupId = "org.ballerinalang"
