[package]
distribution = "2201.7.0"
org="ballerinax"
name = "redis"
version="2.5.0"
authors = ["Ballerina"]
keywords = ["IT Operations/Databases",  "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-redis"
license = ["Apache-2.0"]

[[platform.java11.dependency]]
path = "../redis-utils/build/libs/redis-utils-2.5.0.jar"
groupId = "org.ballerinalang"
artifactId = "redis-utils"
module = "redis-utils" 
version="2.5.0"

[[platform.java11.dependency]]
groupId = "io.lettuce"
artifactId = "lettuce-core"
version = "5.1.2.RELEASE"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "4.1.86.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.1.86.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "4.1.86.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "4.1.86.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.86.Final"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec"
version = "4.1.86.Final"
