[project]
org-name="ballerinax"
version="0.99.0"

[platform]
target = "java11"

[[platform.libraries]]
module = "redis"
path = "../redis-utils/target/redis-0.99.0-SNAPSHOT.jar"
artafactId = "redis"
version = "0.99.0-SNAPSHOT"
groupId = "org.ballerinalang"
